version = 0.1
[default.deploy.parameters]
stack_name = "nexusscan-stack"
resolve_s3 = true
s3_prefix = "nexusscan-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MemorySize=\"1024\" MaxConcurrentScans=\"20\""
image_repositories = []
